version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
      - ./data:/var/lib/mysql
    networks:
      - appnet

  go: 
    image: golang:1.10
    ports:
      - "8000:8000"
    volumes:
      - .:/go/src/github.com/moritzschramm/todo-demo-go
    working_dir: /go/src/github.com/moritzschramm/todo-demo-go
    command: sh run.sh
    networks:
      - appnet
    links:
      - mysql

networks:
  appnet:
    driver: "bridge"

volumes:
  data:
    driver: "local"